raw_training_data = [
        # image_caption
        {"id": "1", "text": "Describe the place I'm in.", "intent": "image_caption"},
        {"id": "2", "text": "What does this environment look like?", "intent": "image_caption"},
        {"id": "3", "text": "Can you tell me about the scene around me?", "intent": "image_caption"},
        {"id": "4", "text": "Describe the atmosphere in this photo.", "intent": "image_caption"},
        {"id": "5", "text": "What are the key elements in this scene?", "intent": "image_caption"},
        {"id": "6", "text": "What can you see in this location?", "intent": "image_caption"},
        {"id": "7", "text": "Summarize the surroundings I’m currently seeing.", "intent": "image_caption"},
        {"id": "8", "text": "Explain the background of this scene.", "intent": "image_caption"},
        {"id": "9", "text": "How does the scene look overall?", "intent": "image_caption"},
        {"id": "10", "text": "Describe the landscape I’m currently seeing.", "intent": "image_caption"},
        {"id": "11", "text": "What is the first impression this place gives?", "intent": "image_caption"},
        {"id": "12", "text": "The scene shows a blend of natural and human-made elements.", "intent": "image_caption"},
        {"id": "13", "text": "Can you give me a detailed description of this view?", "intent": "image_caption"},
        {"id": "14", "text": "Can you describe the atmosphere of the image precisely?", "intent": "image_caption"},
        {"id": "15", "text": "Tell me what’s happening in this image.", "intent": "image_caption"},



        #image_QA

        {"id": "16", "text": "What type is each object shown in the image?", "intent": "image_QA"},
        {"id": "17", "text": "Are the items in the image being used or just present?", "intent": "image_QA"},
        {"id": "18", "text": "Is there interaction between the different items?", "intent": "image_QA"},
        {"id": "19", "text": "Are the objects arranged or scattered randomly?", "intent": "image_QA"},
        {"id": "20", "text": "Are there any broken or old tools?", "intent": "image_QA"},
        {"id": "21", "text": "What materials are the objects made from?", "intent": "image_QA"},
        {"id": "22", "text": "Are the items used to perform a specific task?", "intent": "image_QA"},
        {"id": "23", "text": "Are there signs of frequent use on any of the items?", "intent": "image_QA"},
        {"id": "24", "text": "Are the objects in the image portable?", "intent": "image_QA"},
        {"id": "25", "text": "What kind of clothing are the people wearing?", "intent": "image_QA"},
        {"id": "26", "text": "Are there any signs indicating a specific profession or job?", "intent": "image_QA"},
        {"id": "27", "text": "Are there any logos or brand names visible?", "intent": "image_QA"},
        {"id": "28", "text": "Is there any modern technology visible?", "intent": "image_QA"},
        {"id": "29", "text": "Are there any clear office tools?", "intent": "image_QA"},
        {"id": "30", "text": "Are there noticeable differences between the items (color, size, type)?", "intent": "image_QA"},
        {"id": "31", "text": "Does the image contain consumer products?", "intent": "image_QA"},
        {"id": "32", "text": "What elements indicate a specific activity (cooking, studying, working)?", "intent": "image_QA"},
        {"id": "33", "text": "Are there signs of a home or office setting?", "intent": "image_QA"},
        {"id": "34", "text": "Do the objects suggest a particular season?", "intent": "image_QA"},
        {"id": "35", "text": "Are there items indicating a specific occasion?", "intent": "image_QA"},
        {"id": "36", "text": "What are the edible items in the image?", "intent": "image_QA"},
        {"id": "37", "text": "Are there any cleaning or sanitizing tools?", "intent": "image_QA"},
        {"id": "38", "text": "Are there elements suggesting the presence of children or elderly people?", "intent": "image_QA"},
        {"id": "39", "text": "Do any items reflect culture or religion?", "intent": "image_QA"},
        {"id": "40", "text": "What objects seem abandoned or unused?", "intent": "image_QA"},
        {"id": "41", "text": "Are any items stacked or arranged on top of each other?", "intent": "image_QA"},
        {"id": "42", "text": "What is the most attention-grabbing item in the image?", "intent": "image_QA"},
        {"id": "43", "text": "Are there small elements that are hard to notice?", "intent": "image_QA"},
        {"id": "44", "text": "Is there repetition of certain item types?", "intent": "image_QA"},
        {"id": "45", "text": "Are the items clearly visible or partially hidden?", "intent": "image_QA"},
        {"id": "46", "text": "Is there any object reflecting light or acting as a mirror?", "intent": "image_QA"},
        {"id": "47", "text": "What are the breakable items in the image?", "intent": "image_QA"},
        {"id": "48", "text": "Are there any elements indicating danger or warning?", "intent": "image_QA"},
        {"id": "49", "text": "Are there handmade or crafted items?", "intent": "image_QA"},
        {"id": "50", "text": "What objects indicate time (clock, calendar, sun)?", "intent": "image_QA"},
        {"id": "51", "text": "Is there a mirror or lens in the image?", "intent": "image_QA"},
        {"id": "52", "text": "Are there any sports or exercise equipment?", "intent": "image_QA"},
        {"id": "53", "text": "Are musical instruments visible?", "intent": "image_QA"},
        {"id": "54", "text": "What type of lighting is used?", "intent": "image_QA"},
        {"id": "55", "text": "Are there any tools for writing or drawing?", "intent": "image_QA"},
        {"id": "56", "text": "Are there any tools used for fun or playing?", "intent": "image_QA"},
        {"id": "57", "text": "What kind of surface or flooring is shown in the image?", "intent": "image_QA"},
        {"id": "58", "text": "Are there signs that the place was used recently?", "intent": "image_QA"},
        {"id": "59", "text": "Are there any unusual or specialized electronic tools?", "intent": "image_QA"},
        {"id": "60", "text": "Are there any handmade or traditional-looking items?", "intent": "image_QA"},
        {"id": "61", "text": "How many objects are visible in the image?", "intent": "image_QA"},
        {"id": "62", "text": "How many people are in the scene?", "intent": "image_QA"},
        {"id": "63", "text": "Are there multiple items of the same type?", "intent": "image_QA"},
        {"id": "64", "text": "How many units of this object are visible?", "intent": "image_QA"},
        {"id": "65", "text": "Is the number of items shown considered few or many?", "intent": "image_QA"},
        {"id": "66", "text": "Are there pairs or groups of the same object?", "intent": "image_QA"},
        {"id": "67", "text": "Are the items arranged in rows or organized groups?", "intent": "image_QA"},
        {"id": "68", "text": "Is there only one item of this type?", "intent": "image_QA"},
        {"id": "69", "text": "Which items appear most frequently?", "intent": "image_QA"},
        {"id": "70", "text": "Can the total number of main items be identified?", "intent": "image_QA"},


          #  get_ocr[

        {"id": "70", "text": "Read the text that I see.", "intent": "get_ocr"},
        {"id": "71", "text": "Can you extract any words from this view?", "intent": "get_ocr"},
        {"id": "72", "text": "What text is written here?", "intent": "get_ocr"},
        {"id": "73", "text": "Identify the text that appears in front of me.", "intent": "get_ocr"},
        {"id": "74", "text": "Is there any readable content in this area?", "intent": "get_ocr"},
        {"id": "75", "text": "Extract the written content from what I see.", "intent": "get_ocr"},
        {"id": "76", "text": "What does the text say in this context?", "intent": "get_ocr"},
        {"id": "77", "text": "Does the text follow a certain order (e.g., columns or paragraphs)?", "intent": "get_ocr"},
        {"id": "78", "text": "Are there any dates or numbers mentioned?", "intent": "get_ocr"},
        {"id": "79", "text": "Does the text indicate an official or unofficial document?", "intent": "get_ocr"},
        {"id": "80", "text": "What type of font is used in the text?", "intent": "get_ocr"},
        {"id": "81", "text": "Does the text contain links or web addresses?", "intent": "get_ocr"},
        {"id": "82", "text": "Have parts of the text been blurred or covered?", "intent": "get_ocr"},
        {"id": "83", "text": "Are there logos or institution names written?", "intent": "get_ocr"},
        {"id": "84", "text": "Does the text include instructions or steps to follow?", "intent": "get_ocr"},
        {"id": "85", "text": "Are there words written in a large font or different color?", "intent": "get_ocr"},
        {"id": "86", "text": "What are the prominent phrases or words in the text?", "intent": "get_ocr"},
        {"id": "87", "text": "Does the text refer to a specific place or entity?", "intent": "get_ocr"},
        {"id": "88", "text": "Is the text complete or fragmented?", "intent": "get_ocr"},
        {"id": "89", "text": "Does the text follow a formal document format (e.g., letter or invoice)?", "intent": "get_ocr"},
        {"id": "90", "text": "How many words are written in the image?", "intent": "get_ocr"},
        {"id": "91", "text": "How many lines or paragraphs are in the text?", "intent": "get_ocr"},
        {"id": "92", "text": "Is there repetition of certain words?", "intent": "get_ocr"},
        {"id": "93", "text": "What are the most repeated words in the text?", "intent": "get_ocr"},
        {"id": "94", "text": "Is the text written in the same direction throughout?", "intent": "get_ocr"},
        {"id": "95", "text": "Are there texts that are hard to read due to the image quality?", "intent": "get_ocr"},
        {"id": "96", "text": "Can the content of the text be fully understood from the image?", "intent": "get_ocr"},
        {"id": "97", "text": "Does the text contain symbols or equations?", "intent": "get_ocr"},
        {"id": "98", "text": "Is there part of the text written in italics or bold?", "intent": "get_ocr"},
        {"id": "99", "text": "Are there main or sub-headings?", "intent": "get_ocr"},


          # ask_research_bot
        {"id": "100", "text": "Who is the current president of the United States?", "intent": "ask_research_bot"},
        {"id": "101", "text": "What is the capital of France?", "intent": "ask_research_bot"},
        {"id": "102", "text": "How many continents are there in the world?", "intent": "ask_research_bot"},
        {"id": "103", "text": "What is the largest planet in the solar system?", "intent": "ask_research_bot"},
        {"id": "104", "text": "When was the Declaration of Independence signed?", "intent": "ask_research_bot"},
        {"id": "105", "text": "What is the boiling point of water?", "intent": "ask_research_bot"},
        {"id": "106", "text": "Who wrote the play 'Hamlet'?", "intent": "ask_research_bot"},
        {"id": "107", "text": "Where is London located?", "intent": "ask_research_bot"},
        {"id": "108", "text": "What is the speed of light in a vacuum?", "intent": "ask_research_bot"},
        {"id": "109", "text": "Who discovered gravity?", "intent": "ask_research_bot"},
        {"id": "110", "text": "What is the capital of Japan?", "intent": "ask_research_bot"},
        {"id": "111", "text": "How many planets are in the solar system?", "intent": "ask_research_bot"},
        {"id": "112", "text": "Who is the founder of Microsoft?", "intent": "ask_research_bot"},
        {"id": "113", "text": "What is the longest river in the world?", "intent": "ask_research_bot"},
        {"id": "114", "text": "What is the official language of Brazil?", "intent": "ask_research_bot"},
        {"id": "115", "text": "What is the highest mountain in the world?", "intent": "ask_research_bot"},
        {"id": "116", "text": "Who was the first human in space?", "intent": "ask_research_bot"},
        {"id": "117", "text": "What is the official currency of the United Kingdom?", "intent": "ask_research_bot"},
        {"id": "118", "text": "What is the chemical element with the symbol O?", "intent": "ask_research_bot"},
        {"id": "119", "text": "Who is the author of the novel 'One Hundred Years of Solitude'?", "intent": "ask_research_bot"},
        {"id": "120", "text": "Which country has the largest population in the world?", "intent": "ask_research_bot"},
        {"id": "121", "text": "How many sides does a triangle have?", "intent": "ask_research_bot"},
        {"id": "122", "text": "What is the national animal of Egypt?", "intent": "ask_research_bot"},
        {"id": "123", "text": "What is the name of the planet closest to the sun?", "intent": "ask_research_bot"},
        {"id": "124", "text": "In what year did World War II begin?", "intent": "ask_research_bot"},
        {"id": "125", "text": "Who is the current president of the United States?", "intent": "ask_research_bot"},
        {"id": "126", "text": "What is the capital of France?", "intent": "ask_research_bot"},
        {"id": "127", "text": "How many continents are there?", "intent": "ask_research_bot"},
        {"id": "128", "text": "What is the largest planet in our solar system?", "intent": "ask_research_bot"},
        {"id": "129", "text": "When was the Declaration of Independence signed?", "intent": "ask_research_bot"},
        {"id": "130", "text": "What is the boiling point of water?", "intent": "ask_research_bot"},
        {"id": "131", "text": "Who wrote 'Hamlet'?", "intent": "ask_research_bot"},
        {"id": "132", "text": "Where is London?", "intent": "ask_research_bot"},
        {"id": "133", "text": "What's the latest news?", "intent": "ask_research_bot"},
        {"id": "134", "text": "Tell me about today's headlines.", "intent": "ask_research_bot"},
        {"id": "135", "text": "What is happening in the world right now?", "intent": "ask_research_bot"},
        {"id": "136", "text": "Give me the latest sports updates.", "intent": "ask_research_bot"},
        {"id": "137", "text": "What's trending on social media?", "intent": "ask_research_bot"},
        {"id": "138", "text": "What are the latest political developments?", "intent": "ask_research_bot"},
        {"id": "139", "text": "Are there any updates on major world events?", "intent": "ask_research_bot"},
        {"id": "140", "text": "What's new in the world of technology?", "intent": "ask_research_bot"},
        {"id": "141", "text": "Can you provide updates on any ongoing crises?", "intent": "ask_research_bot"},
        {"id": "142", "text": "What’s the latest in entertainment news?", "intent": "ask_research_bot"},
        {"id": "143", "text": "Are there any weather alerts for today?", "intent": "ask_research_bot"},
        {"id": "144", "text": "What’s trending in global finance today?", "intent": "ask_research_bot"},
        {"id": "145", "text": "Any major breakthroughs in science today?", "intent": "ask_research_bot"},
        {"id": "146", "text": "What cultural events are happening this week?", "intent": "ask_research_bot"},
        {"id": "147", "text": "Is there any breaking news about natural disasters?", "intent": "ask_research_bot"},
        {"id": "148", "text": "What are the latest updates on COVID-19 or health news?", "intent": "ask_research_bot"},



        # Time Intents

        {"id": "149", "text": "What time is it?", "intent": "time"},
        {"id": "150", "text": "Can you tell me the current time?", "intent": "time"},
        {"id": "151", "text": "What time zone am I in?", "intent": "time"},
        {"id": "152", "text": "What's the time difference between here and London?", "intent": "time"},
        {"id": "153", "text": "How many hours until midnight?", "intent": "time"},
        {"id": "154", "text": "What clock is now?", "intent": "time"},
        {"id": "155", "text": "What time is sunset exactly today?", "intent": "time"},
        {"id": "156", "text": "When exactly does daylight saving time end this year?", "intent": "time"},
        {"id": "157", "text": "Can you give me the precise time difference between New York and Tokyo?", "intent": "time"},
        {"id": "158", "text": "How many exact minutes have passed since noon?", "intent": "time"},
        {"id": "159", "text": "If it’s 9 AM in London, what is the exact time for my meeting tomorrow?", "intent": "time"},
        {"id": "160", "text": "What will the exact time be in 5 hours from now?", "intent": "time"},
        {"id": "161", "text": "What is the precise moment when daylight saving time starts this year?", "intent": "time"},
        {"id": "162", "text": "What is the exact current time in Sydney, down to the second?", "intent": "time"},
        {"id": "163", "text": "How many days exactly until the next leap year begins?", "intent": "time"},
        {"id": "164", "text": "Can you tell me the exact difference in hours between my location and Paris?", "intent": "time"},
        {"id": "165", "text": "What is the exact date and time right now?", "intent": "time"},
        {"id": "166", "text": "How many exact hours are left until my birthday?", "intent": "time"},
        {"id": "167", "text": "What is the exact time zone of California?", "intent": "time"},
        {"id": "168", "text": "When exactly does the next daylight saving change occur?", "intent": "time"},
        {"id": "169", "text": "What is the exact length of daylight today in my location?", "intent": "time"},
        {"id": "170", "text": "Can you remind me of the precise time for my flight tomorrow?", "intent": "time"},
        {"id": "171", "text": "What is the exact time zone of New Delhi, including any offsets?", "intent": "time"},
        {"id": "172", "text": "How many exact hours are left until 5 PM today?", "intent": "time"},
        {"id": "173", "text": "What is the precise current date and time in UTC?", "intent": "time"},
        {"id": "174", "text": "When exactly is the next full moon?", "intent": "time"},
        {"id": "175", "text": "How many exact days are left until the end of the year?", "intent": "time"},
        {"id": "176", "text": "What is the exact number of days left in this month?", "intent": "time"},
        {"id": "177", "text": "Can you give me the exact time difference between here and Brazil?", "intent": "time"},
        {"id": "178", "text": "When exactly does summer begin this year?", "intent": "time"},
        {"id": "179", "text": "How many exact days are left until next Friday?", "intent": "time"},
        {"id": "180", "text": "When precisely does winter start this year?", "intent": "time"},
        {"id": "181", "text": "How many exact hours are left until the end of the week?", "intent": "time"},
        {"id": "182", "text": "How long exactly does it take for Earth to orbit the sun?", "intent": "time"},
        {"id": "183", "text": "What is the exact number of hours in a week?", "intent": "time"},
        {"id": "184", "text": "How many exact months are left until the end of the year?", "intent": "time"},
        {"id": "185", "text": "Can you set an alarm for exactly 7 AM tomorrow?", "intent": "time"},
        {"id": "186", "text": "What is the exact time for the eclipse?", "intent": "time"},
        {"id": "187", "text": "When exactly is the next leap year?", "intent": "time"},
        {"id": "188", "text": "What is the precise time difference between New York and Beijing?", "intent": "time"},
        {"id": "189", "text": "How many exact hours are left until the next new year?", "intent": "time"},
        {"id": "190", "text": "What is the exact number of seconds in a day?", "intent": "time"},
        {"id": "191", "text": "How many exact hours have passed since midnight?", "intent": "time"},
        {"id": "192", "text": "When does the next season start exactly?", "intent": "time"},



        # ask_bot

        {"id": "193", "text": "Hi there, how are you today?", "intent": "ask_bot"},
        {"id": "194", "text": "What can I do for you today?", "intent": "ask_bot"},
        {"id": "195", "text": "Tell me something fun.", "intent": "ask_bot"},
        {"id": "196", "text": "Can you help me with a task?", "intent": "ask_bot"},
        {"id": "197", "text": "What do you think about the latest technology?", "intent": "ask_bot"},
        {"id": "198", "text": "Can you suggest something to do for fun?", "intent": "ask_bot"},
        {"id": "199", "text": "suggest movies or books?", "intent": "ask_bot"},
        {"id": "200", "text": "What’s your favorite thing to talk about?", "intent": "ask_bot"},
        {"id": "201", "text": "Can you tell me a joke?", "intent": "ask_bot"},
        {"id": "202", "text": "something interesting to learn about", "intent": "ask_bot"},
        {"id": "203", "text": "I’ve been thinking about trying something new.", "intent": "ask_bot"},
        {"id": "204", "text": "I’m curious about your thoughts on creativity.", "intent": "ask_bot"},
        {"id": "205", "text": "I love learning new things. Got any ideas?", "intent": "ask_bot"},
        {"id": "206", "text": "What’s something you like talking about?", "intent": "ask_bot"},
        {"id": "207", "text": "Tell me about your favorite hobbies.", "intent": "ask_bot"},
        {"id": "208", "text": "What’s something you enjoy doing in your free time?", "intent": "ask_bot"},
        {"id": "209", "text": "I’ve been exploring different topics lately.", "intent": "ask_bot"},
        {"id": "210", "text": "Do you ever get bored? What do you do?", "intent": "ask_bot"},


        #  add_memory
      
        {"id": "211", "text": "Add a new image.", "intent": "add_memory"},
        {"id": "212", "text": "Record some text.", "intent": "add_memory"},
        {"id": "213", "text": "Write important information.", "intent": "add_memory"},
        {"id": "214", "text": "Combine an image with a description.", "intent": "add_memory"},
        {"id": "215", "text": "Enter the image link.", "intent": "add_memory"},
        {"id": "216", "text": "Add a caption to the image.", "intent": "add_memory"},
        {"id": "217", "text": "Record the image name.", "intent": "add_memory"},
        {"id": "218", "text": "Share image details.", "intent": "add_memory"},
        {"id": "219", "text": "Link an image with information.", "intent": "add_memory"},
        {"id": "220", "text": "Place text next to the image.", "intent": "add_memory"},
        {"id": "221", "text": "Add a title with the image.", "intent": "add_memory"},
          

        {"id": "222", "text": "Sounds good", "intent": "yes"},
        {"id": "223", "text": "Alright", "intent": "yes"},
        {"id": "224", "text": "Sure thing", "intent": "yes"},
        {"id": "225", "text": "Definitely", "intent": "yes"},
        {"id": "226", "text": "Absolutely", "intent": "yes"},
        {"id": "227", "text": "Of course", "intent": "yes"},
        {"id": "228", "text": "Fine by me", "intent": "yes"},
        {"id": "229", "text": "That's okay", "intent": "yes"},
        {"id": "230", "text": "I’m in", "intent": "yes"},
        {"id": "231", "text": "Go ahead", "intent": "yes"},
        {"id": "232", "text": "No problem", "intent": "yes"},
        {"id": "233", "text": "Okay then", "intent": "yes"},
        {"id": "234", "text": "I’m good with that", "intent": "yes"},
        {"id": "235", "text": "That’s fine", "intent": "yes"},
        {"id": "236", "text": "I accept", "intent": "yes"},
        {"id": "237", "text": "That works", "intent": "yes"},
        {"id": "238", "text": "It’s fine", "intent": "yes"},
        {"id": "239", "text": "Go for it", "intent": "yes"},
        {"id": "240", "text": "I'm okay with that", "intent": "yes"},
        {"id": "241", "text": "Cool with me", "intent": "yes"},
        {"id": "242", "text": "yes", "intent": "yes"},
        {"id": "243", "text": "sure", "intent": "yes"},
        {"id": "244", "text": "true", "intent": "yes"},



        {"id": "246", "text": "I don’t agree", "intent": "no"},
        {"id": "247", "text": "Not really", "intent": "no"},
        {"id": "248", "text": "Nope", "intent": "no"},
        {"id": "249", "text": "I don’t think so", "intent": "no"},
        {"id": "250", "text": "Absolutely not", "intent": "no"},
        {"id": "251", "text": "I'm not okay with that", "intent": "no"},
        {"id": "252", "text": "That's not fine", "intent": "no"},
        {"id": "253", "text": "Not at all", "intent": "no"},
        {"id": "254", "text": "I’d rather not", "intent": "no"},
        {"id": "255", "text": "No way", "intent": "no"},
        {"id": "256", "text": "That's not acceptable", "intent": "no"},
        {"id": "257", "text": "I reject that", "intent": "no"},
        {"id": "258", "text": "Count me out", "intent": "no"},
        {"id": "259", "text": "That doesn't work for me", "intent": "no"},
        {"id": "260", "text": "Sorry, no", "intent": "no"},
        {"id": "261", "text": "I’m not in", "intent": "no"},
        {"id": "262", "text": "I can’t accept that", "intent": "no"},
        {"id": "263", "text": "Not interested", "intent": "no"},
        {"id": "264", "text": "Negative", "intent": "no"},
        {"id": "265", "text": "No deal", "intent": "no"},
        {"id": "266", "text": "I disagree", "intent": "no"},
        {"id": "267", "text": "That's not okay", "intent": "no"},
        {"id": "268", "text": "no", "intent": "no"},
        {"id": "269", "text": "false", "intent": "no"},

        # get_face
        {"id": "270", "text": "Do you know who this is?", "intent": "get_face"},
        {"id": "271", "text": "Can you tell who this person is?", "intent": "get_face"},
        {"id": "272", "text": "Is this face recognized?", "intent": "get_face"},
        {"id": "273", "text": "Who's in the image?", "intent": "get_face"},
        {"id": "274", "text": "Identify the person in this image.", "intent": "get_face"},
        {"id": "275", "text": "Can AI detect who this is?", "intent": "get_face"},
        {"id": "276", "text": "Tell me who this person is.", "intent": "get_face"},
        {"id": "277", "text": "Whose face is this?", "intent": "get_face"},
        {"id": "278", "text": "Can you match this face to a name?", "intent": "get_face"},
        {"id": "279", "text": "Recognize the person in this photo?", "intent": "get_face"},

        #get_facenum

        {"id": "280", "text": "How many people are in this group?", "intent": "get_facenum"},
        {"id": "281", "text": "Can you count the faces in this group photo?", "intent": "get_facenum"},
        {"id": "282", "text": "How many people are shown in this snapshot?", "intent": "get_facenum"},
        {"id": "283", "text": "Is there more than one face in this picture?", "intent": "get_facenum"},
        {"id": "284", "text": "How many individuals are in this image?", "intent": "get_facenum"},
        {"id": "285", "text": "Can you identify the number of people in this photo?", "intent": "get_facenum"},
        {"id": "286", "text": "How many people are visible in this photo?", "intent": "get_facenum"},
        {"id": "287", "text": "Can you tell how many people are in this image?", "intent": "get_facenum"},
        {"id": "288", "text": "Are there multiple people in this photo?", "intent": "get_facenum"},
        {"id": "289", "text": "How many people are visible in this scene?", "intent": "get_facenum"},
        {"id": "290", "text": "How many people can be seen in this image?", "intent": "get_facenum"},
        {"id": "291", "text": "Is this image of a group of people?", "intent": "get_facenum"},
        {"id": "292", "text": "Can you count how many people are shown here?", "intent": "get_facenum"},
        {"id": "293", "text": "How many faces are visible in this picture?", "intent": "get_facenum"},
        {"id": "294", "text": "Can you tell the number of people in this image?", "intent": "get_facenum"},
        {"id": "295", "text": "How many individuals can be seen in this photo?", "intent": "get_facenum"},
        {"id": "296", "text": "How many people are there in this picture?", "intent": "get_facenum"},
        {"id": "297", "text": "Can you count the faces in this photo?", "intent": "get_facenum"},
        {"id": "298", "text": "Is there only one face in this picture?", "intent": "get_facenum"},
        {"id": "299", "text": "How many faces can you identify in this picture?", "intent": "get_facenum"},
        {"id": "300", "text": "Can you identify how many faces are visible?", "intent": "get_facenum"},

        #ask_memory

        {"id": "301", "text": "Can you remind me of what I saved last time?", "intent": "ask_memory"},
        {"id": "302", "text": "What information have you stored for me?", "intent": "ask_memory"},
        {"id": "303", "text": "Do you remember the last thing I told you?", "intent": "ask_memory"},
        {"id": "304", "text": "Can you show me my saved memories?", "intent": "ask_memory"},
        {"id": "305", "text": "What did I ask you about earlier?", "intent": "ask_memory"},
        {"id": "306", "text": "Can you retrieve the last note I saved?", "intent": "ask_memory"},
        {"id": "307", "text": "Do you have any reminders stored for me?", "intent": "ask_memory"},
        {"id": "308", "text": "What’s the last thing you remember?", "intent": "ask_memory"},
        {"id": "309", "text": "Can you recall the information you’ve stored in your memory?", "intent": "ask_memory"},
        {"id": "310", "text": "Do you remember our last conversation?", "intent": "ask_memory"},
        {"id": "311", "text": "What did I ask you to remember yesterday?", "intent": "ask_memory"},
        {"id": "312", "text": "Do you remember any important details I shared with you?", "intent": "ask_memory"},
        {"id": "313", "text": "What’s the most recent memory you’ve saved for me?", "intent": "ask_memory"},
        {"id": "314", "text": "Can you list the things you’ve stored in your memory?", "intent": "ask_memory"},
        {"id": "315", "text": "Have you saved any reminders for me today?", "intent": "ask_memory"},

        #hello
        {"id": "316", "text": "Hello there!", "intent": "hello"},
        {"id": "317", "text": "Hey, how's everything?", "intent": "hello"},
        {"id": "318", "text": "What's happening?", "intent": "hello"},
        {"id": "319", "text": "What's up with you?", "intent": "hello"},
        {"id": "320", "text": "Hey, how are you doing?", "intent": "hello"},
        {"id": "321", "text": "Good to see you again!", "intent": "hello"},
        {"id": "322", "text": "Nice to see you!", "intent": "hello"},
        {"id": "323", "text": "Yo, what's up?", "intent": "hello"},
        {"id": "324", "text": "Hello, how have you been?", "intent": "hello"},
        {"id": "325", "text": "Hey! Long time no see!", "intent": "hello"},
        {"id": "326", "text": "What's going on?", "intent": "hello"},
        {"id": "327", "text": "Hi, how's life?", "intent": "hello"},
        {"id": "328", "text": "Hello, my friend!", "intent": "hello"},
        {"id": "329", "text": "Hey, how’s everything going?", "intent": "hello"},
        {"id": "330", "text": "Hey, how's your day?", "intent": "hello"},

]